name: Build, Sync and Deploy

on:
  push:
    branches: ["main"]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-sync-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ELM
        uses: actions/checkout@v4

      - name: Install Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build ELM
        run: bun run build

      - name: Commit dist back to repo
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: sync production build [skip ci]"
          file_pattern: 'dist/*'

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
